SELECT
        [TreatmentIDLook]
      ,[TreatmentProductSequence]
      ,[TreatmentRanked]
      ,[TreatmentIDBook]
      ,[QuantityBooked]
      ,[FinalStage]
      ,[ProductID]
      ,[ProductName]
      ,[AmountReport]
      ,[CurrencyCodeReport]
      ,[Amount]
      ,[OriginalPrice]
      ,[CurrencyCode]
      ,[QuantityAvailable]
      ,[CalculatedFrom]
      ,[GroupCode]
      ,[TreatmentOrdinal]
      ,[TreatmentIDLookByProduct]
      ,[OfferCode]
      ,[OptimizedPoints]
      ,tdr.[MinLoggedUTC]
  FROM [ANAJQDW01].[AnalyticsDW].[TreatmentProductRanked] tpr
 INNER JOIN [ANAJQDW01].[AnalyticsDW].[TreatmentDistinctRanked] tdr ON tpr.[TreatmentIDLook] = tdr.[MinTreatmentID]
  WHERE tdr.[MinTreatmentID] > %s and tdr.[MinTreatmentID] < %s
